// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA0rQAXKXOQwcJ6DPaMSXyA3MMi8CswkE',
    appId: '1:550758439466:web:7ee5728ddb20634d19c153',
    messagingSenderId: '550758439466',
    projectId: 'flutter-app-2026-acb44',
    authDomain: 'flutter-app-2026-acb44.firebaseapp.com',
    storageBucket: 'flutter-app-2026-acb44.firebasestorage.app',
    measurementId: 'G-S0RGTHGQKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx_AhP0euCeudfKdSyIEICrZEO-FoOjDA',
    appId: '1:550758439466:android:47a8f6908caacbb719c153',
    messagingSenderId: '550758439466',
    projectId: 'flutter-app-2026-acb44',
    storageBucket: 'flutter-app-2026-acb44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZRSrnVGf9H1pPAwqUArtt8RtzGTkg40E',
    appId: '1:550758439466:ios:fd023636964025c119c153',
    messagingSenderId: '550758439466',
    projectId: 'flutter-app-2026-acb44',
    storageBucket: 'flutter-app-2026-acb44.firebasestorage.app',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZRSrnVGf9H1pPAwqUArtt8RtzGTkg40E',
    appId: '1:550758439466:ios:fd023636964025c119c153',
    messagingSenderId: '550758439466',
    projectId: 'flutter-app-2026-acb44',
    storageBucket: 'flutter-app-2026-acb44.firebasestorage.app',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA0rQAXKXOQwcJ6DPaMSXyA3MMi8CswkE',
    appId: '1:550758439466:web:9d4486b02bcfb49d19c153',
    messagingSenderId: '550758439466',
    projectId: 'flutter-app-2026-acb44',
    authDomain: 'flutter-app-2026-acb44.firebaseapp.com',
    storageBucket: 'flutter-app-2026-acb44.firebasestorage.app',
    measurementId: 'G-1FC3MDW5LQ',
  );
}